In [1]:
# ziad aburas group A
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print("1. array():", arr1)

1. array(): [1 2 3 4 5]


In [15]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(f"array shape : {arr2.shape}")


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
array shape : (2, 5)


In [16]:
arr3= arr2.reshape(5,2)
print(f"reshaped array {arr3} \n new shape : {arr3.shape}")

reshaped array [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 
 new shape : (5, 2)


In [17]:
arr4= arr3.reshape(-1)
print(f"1d array : {arr4}")

1d array : [ 1  2  3  4  5  6  7  8  9 10]


In [20]:
print(f"sub array 1-5 : {arr4[:5]}")
print(f"sub array three elements in end : {arr4[-3:]}")

sub array 1-5 : [1 2 3 4 5]
sub array three elements in end : [ 8  9 10]


In [27]:
arr5= arr4.astype('U')
print(f"last type : {arr4.dtype}",arr4)
print(f"new type : {arr5.dtype}",arr5)

last type : int64 [ 1  2  3  4  5  6  7  8  9 10]
new type : <U21 ['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [29]:
# accses 1d array
sum=0
for x in arr4:
  sum+=x
print(f"sum of array elements : {sum}")

sum of array elements : 55


In [35]:
# acces multi dim array
print("normal ")
for x in arr2:
  for y in x:
    print(y,end='')
print("\nusing nditer")
for x in np.nditer(arr2):
  print(x,end='')
print("\nwith index")
for i,x in np.ndenumerate(arr2):
  print(i,x)


normal 
12345678910
using nditer
12345678910
with index
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10


In [48]:
arr6 = np.concatenate((arr2.reshape(2,5), arr3.reshape(2,5)))
print(f"arr2 : \n{arr2}\n\narr3 : \n {arr3} \n\nconcatenated array : \n{arr6}")

arr2 : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

arr3 : 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 

concatenated array : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [51]:
# acces elements using condition
print(f"arr2 ",arr2)
print(f"even nums in arr2 : {arr2[arr2%2==0]}")

arr2  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
even nums in arr2 : [ 2  4  6  8 10]
